name: Deploy to staging
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy App to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@${{ secrets.SERVER_HOST }} "
            export NVM_DIR=\"/home/ubuntu/.nvm\"
            [ -s \"\$NVM_DIR/nvm.sh\" ] && . \"\$NVM_DIR/nvm.sh\"
            cd learning-ci-cd-deployment &&
            npm install -g pnpm &&
            pnpm install &&
            pnpm run build &&
            pm2 restart fe-server ||
            pm2 start apps/web --name fe-server --watch &&
            pm2 restart http-server ||
            pm2 start apps/http-server --name http-server --watch &&
            pm2 restart ws-server ||
            pm2 start apps/ws-server --name ws-server --watch
          "


