name: Deploy to staging

on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploy everything to the staging cluster

    steps:
      - name: Copy Repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOST }}" > ~/.ssh/known_hosts

      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=yes -i ~/ssh_key root@65.0.184.158 "
            cd learning-ci-cd-deployment &&
            git pull &&
            pnpm install &&
            pnpm run build &&
            pm2 restart fe-server &&
            pm2 restart http-server &&
            pm2 restart ws-server
          "
